Updated dependencies, cleaned up code

diff --git a/vendor/github.com/steven-xie/glip/Makefile b/vendor/github.com/steven-xie/glip/Makefile
--- a/vendor/github.com/steven-xie/glip/Makefile
+++ b/vendor/github.com/steven-xie/glip/Makefile
@@ -23,12 +23,12 @@ run:
 	@if [ -f ".env.sh" ]; then \
 	   printf 'Exporting environment variables by sourcing ".env.sh"... '; \
 	   . .env.sh; \
-	   echo "done."; \
+	   printf "done.\n"; \
 	 fi
 	@if [ -f "$(PKG_NAME)" ]; then \
-	   echo 'Running "$(PKG_NAME)"...'; \
+	   printf 'Running "$(PKG_NAME)"...\n'; \
 	   ./$(PKG_NAME); \
-	 else echo '[ERROR] Could not find program "$(PKG_NAME)".'; \
+	 else printf '[ERROR] Could not find program "$(PKG_NAME)".\n'; \
 	 fi
 
 ## Builds the program specified by the main package.
@@ -36,20 +36,20 @@ build:
 	@printf "Building... "
 	@GOBUILD_OUT="$$(go build 2>&1)"; \
 		if [ -n "$$GOBUILD_OUT" ]; then \
-		  echo "\n[ERROR] Failed to build program:"; \
-		  echo $$GOBUILD_OUT; \
-		  return 1; \
-		else echo "done."; \
+		  printf "\n[ERROR] Failed to build program:\n"; \
+		  printf "$$GOBUILD_OUT\n"; \
+		  exit 1; \
+		else printf "done.\n"; \
 		fi
 
 install:
 	@printf 'Installing with "go install"... '
 	@GOINSTALL_OUT="$$(go install 2>&1)"; \
 		if [ -n "$$GOBUILD_OUT" ]; then \
-		  echo "\n[ERROR] failed to install:"; \
-		  echo "$$GOINSTALL_OUT"; \
-		  return 1; \
-		else echo "done."; \
+		  printf "\n[ERROR] failed to install:\n"; \
+		  printf "$$GOINSTALL_OUT\n"; \
+		  exit 1; \
+		else printf "done.\n"; \
 		fi
 
 
@@ -58,10 +58,10 @@ get:
 	@printf 'Installing package dependencies with "go get"... '
 	@GOGET_OUT="$$(go get ./... 2>&1)"; \
 		if [ -n "$$GOGET_OUT" ]; then \
-		  echo "\n[ERROR] Failed to install package dependencies:"; \
-		  echo "$$GOGET_OUT"; \
-		  return 1; \
-		else echo "done."; \
+		  printf "\n[ERROR] Failed to install package dependencies:\n"; \
+		  printf "$$GOGET_OUT\n"; \
+		  exit 1; \
+		else printf "done.\n"; \
 		fi
 
 ## Installs and updates package dependencies.
@@ -69,19 +69,22 @@ update:
 	@printf 'Installing and updating package dependencies with "go get"... '
 	@GOGET_OUT="$$(go get -u 2>&1)"; \
 			if [ -n "$$GOGET_OUT" ]; then \
-		  echo "\n[ERROR] Failed to install package dependencies:"; \
-		  echo "$$GOGET_OUT"; \
-		  return 1; \
-		else echo "done."; \
+		  printf "\n[ERROR] Failed to install package dependencies:\n"; \
+		  printf "$$GOGET_OUT\n"; \
+		  exit 1; \
+		else printf "done.\n"; \
 		fi
 
 
 ## Formats, checks, and tests the code.
 review: fmt check test
+review-v: fmt check test-v
 ## Like "review", but tests for race conditions.
 review-race: fmt check test-race
+review-race-v: fmt check test-race-v
 ## Like "review-race", but includes benchmarks.
-review-bench: fmt check test-race bench
+review-bench: review-race bench
+review-bench-v: review-race bench-v
 
 
 ## Checks for formatting, linting, and suspicious code.
@@ -90,11 +93,11 @@ check:
 	@printf "Check fmt...                 "
 	@GOFMT_OUT="$$(gofmt -l $(SRC_FILES) 2>&1)"; \
 		if [ -n "$$GOFMT_OUT" ]; then \
-		  echo '\n[WARN] Fix formatting issues in the following files with \
-"make fmt":'; \
-		  echo "$$GOFMT_OUT\n"; \
-		  return 1; \
-		else echo "ok"; \
+		  printf '\n[WARN] Fix formatting issues in the following files with \
+"make fmt":\n'; \
+		  printf "$$GOFMT_OUT\n"; \
+		  exit 1; \
+		else printf "ok\n"; \
 		fi
 ## Lint files...
 	@printf "Check lint...                "
@@ -102,20 +105,20 @@ check:
 		if [ -n "$$GOLINT_OUT" ]; then \
 		  printf "\n"; \
 		  for PKG in "$$GOLINT_OUT"; do \
-		    echo "$$PKG"; \
+		    printf "$$PKG\n"; \
 		  done; \
 		  printf "\n"; \
-		  return 1; \
-		else echo "ok"; \
+		  exit 1; \
+		else printf "ok\n"; \
 		fi
 ## Check suspicious code...
 	@printf "Check vet...                 "
 	@GOVET_OUT="$$(go vet 2>&1)"; \
 		if [ -n "$$GOVET_OUT" ]; then \
-		  echo '\n[WARN] Fix suspicious code from "go vet":'; \
-		  echo "$$GOVET_OUT\n"; \
-		  return 1; \
-		else echo "ok"; \
+		  printf '\n[WARN] Fix suspicious code from "go vet":\n'; \
+		  printf "$$GOVET_OUT\n"; \
+		  exit 1; \
+		else printf "ok\n"; \
 		fi
 
 ## Reformats code according to "gofmt".
@@ -124,8 +127,8 @@ fmt:
 	@GOFMT_OUT="$$(gofmt -l -s -w $(SRC_FILES) 2>&1)"; \
 	 if [ -n "$$GOFMT_OUT" ]; then \
 	 	printf "\n$$GOFT_OUT\n"; \
-	 	return 1; \
-	 else echo "ok"; \
+	 	exit 1; \
+	 else printf "ok\n"; \
      fi;
 
 ## Testing commands:
@@ -133,14 +136,24 @@ GOTEST = go test ./... -coverprofile=$(COVER_OUT) \
 		               -covermode=atomic \
 		               -timeout=$(TEST_TIMEOUT)
 test:
-	@echo "Testing:"
+	@printf "Testing:\n"
 	@$(GOTEST)
 test-v:
-	@echo "Testing (verbose):"
+	@printf "Testing (verbose):\n"
 	@$(GOTEST) -v
+
+GOTEST_RACE = $(GOTEST) -race
 test-race:
-	@echo "Testing (race):"
-	@$(GOTEST) -race
+	@printf "Testing (race):\n"
+	@$(GOTEST_RACE)
+test-race-v:
+	@printf "Testing (race, verbose):\n"
+	@$(GOTEST_RACE) -v
+
+GOBENCH = $(GOTEST) ./... -run=^$ -bench=. -benchmem
 bench:
-	@echo "Benchmarking..."
-	@go test ./... -run=^$ -bench=. -benchmem
+	@printf "Benchmarking:\n"
+	@$(GOBENCH)
+bench-v:
+	@printf "Benchmarking (verbose):\n"
+	@$(GOBENCH) -v
